version: 2
updates:
  # GitHub Actions überwachen (CI/CD)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # npm-Pakete (z. B. wenn du marked.js oder andere Libs lokal verwaltest)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  # Web (HTML/CSS/JS via CDN) wird nicht direkt gescannt, aber du kannst Notification-Tracking erzwingen:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
